[book]
authors = ["安竹 洋平"]
language = "ja"
multilingual = false
src = "src"
title = "ディスレクシアまとめ"
description = "「読むこと」もしくは「書くこと」に困難さを抱える障害である「ディスレクシア」についての全般的な情報を、周知啓発のためにまとめています。少なく見積もっても人口の2.5%が読み書きに著しい困難さを抱えています。"

[output.html]
theme = "src/theme"
git-repository-url="https://github.com/yasutakeyohei/dyslexia"
google-analytics="UA-144705402-1"
# additional-js=["growl-notification/growl-notification.min.js", "register-sw.js", "notification.js", "medium-zoom.js"]
# additional-css=["growl-notification/light-theme.min.css"]
# additional-css=["./src/mdbook-shared/custom.css"]
# additional-js=["./src/mdbook-shared/medium-zoom.js", "./src/mdbook-shared/a11y.js"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = false

[output.z]
command = "python ../../postprocess.py"
optional = true

[output.html.redirect]
"./gigaschool.html" = "./news/20201030_giga-school.html"
"./laws/barrier-free.html" = "./dokusyo-barrier-free.html"
"./hairyo/index.html" = "../gouriteki-hairyo/"
"./hairyo/jouhou-hosyo.html" = "../gouriteki-hairyo/jouhou-hosyo.html"
"./hairyo/jugyo-school-life.html" = "../gouriteki-hairyo/jouhou-hosyo.html"
"./hairyo/juken.html" = "../gouriteki-hairyo/juken.html"
